#spring:
#  # DataSource Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://43.142.117.210:3306/wanwu_code_api
#    username: root
#    password: jinli
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#  # session 失效时间（分钟）
#  session:
#    timeout: 86400
#    store-type: none
#  # redis 配置
#  redis:
#    port: 6379
#    host: 43.142.117.210
#    database: 4
#    password: 117210
#server:
#  port: 8805
#  servlet:
#    context-path: /api
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
##登录相关
############### Sa-Token 配置 (文档: https://sa-token.cc) ##############
#sa-token:
#  # token 名称（同时也是 cookie 名称）
#  token-name: wanwu-sa-token
#  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
#  timeout: 2592000
#  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
#  active-timeout: -1
#  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
#  is-concurrent: true
#  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
#  is-share: true
#  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
#  token-style: tik
#  # 是否输出操作日志
#  is-log: true
#wanwu:
#  api:
#    client:
#      access-key: xxxx
#      secret-key: xxxx
#
